version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  flaskapp:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app/__init__.py
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      MONGO_URI: mongodb+srv://admin:admin@wifi.otc2thm.mongodb.net/
      MONGO_DB_NAME: wifi_points_db
    depends_on:
      - mongo
